server:
  port: 7001
spring:
  config:
    name: ravenbooks-product
---
spring:
  profiles: local
  h2:
    console:
      enabled: true
      path: /h2-console
  kafka:
    producer:
      bootstrap-servers:
      retries: 3
      acks: 1
      client-id: product-${random.uuid}
      security:
        protocol: PLAINTEXT
  jpa:
    hibernate:
      ddl-auto: create-drop
axon:
  kafka:
    default-topic: local.event
    bootstrap-servers: localhost:9092
    publisher:
      confirmation-mode: transactional
    producer:
      retries: 0
      event-processor-mode: subscribing
    consumer:
      client-id: product-${spring.profiles}
  axonserver:
    enabled: false

  serializer:
    events: jackson
---
spring:
  profiles: cloud
