server:
  port: 7001
spring:
  config:
    name: ravenbooks-product
---
spring:
  profiles: local
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
axon:
  kafka:
    default-topic: local.event
    bootstrap-servers: localhost:9092
    publisher:
      confirmation-mode: transactional
    producer:
      retries: 0
      event-processor-mode: subscribing
      transaction-id-prefix: product-${spring.profiles}
    fetcher:
      poll-timeout: 3000
    consumer:
      enable-auto-commit: true
      auto-commit-interval: 3000
      event-processor-mode: tracking
    client-id: product-${spring.profiles}-${random.uuid}
    properties:
      security.protocol: PLAINTEXT
#  axonserver:
#    enabled: true
#    client-id: product-${spring.profiles}-${random.uuid}
#    commit-timeout: 1000
  serializer:
    events: jackson
---
spring:
  profiles: cloud
