version: "3.3"
services:
  microservice_mysql:
    image: mysql:8.0.21
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ROOT_PW
      MYSQL_DATABASE: product_db
      MYSQL_USER: product_user
      MYSQL_PASSWORD: P@ssw0rd12345
volumes:
  db_data: {}

